apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: movies-service
  name: movies-service
spec:
  ports:
  - name: "3004"
    port: 3004
    targetPort: 3000
  selector:
    io.kompose.service: movies-service
  type: LoadBalancer
status:
  loadBalancer: {}
