apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: movies-db
  name: movies-db
spec:
  ports:
  - name: "4004"
    port: 4004
    targetPort: 5432
  selector:
    io.kompose.service: movies-db
  type: NodePort
status:
  loadBalancer: {}
