apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: users-service
  name: users-service
spec:
  ports:
  - name: "3002"
    port: 3002
    targetPort: 3000
  selector:
    io.kompose.service: users-service
  type: LoadBalancer
status:
  loadBalancer: {}
