apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: users-db
  name: users-db
spec:
  ports:
  - name: "4002"
    port: 4002
    targetPort: 5432
  selector:
    io.kompose.service: users-db
  type: NodePort
status:
  loadBalancer: {}
